<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitReportReporter -->
<testsuite skipped="0" hostname="MAVBCP778" name="com.CucumberRunner_Assignment3" tests="19" failures="0" timestamp="2020-08-06T16:48:33 IST" time="167.916" errors="5">
  <testcase name="scenario" time="5.106" classname="com.CucumberRunner_Assignment3">
    <error type="com.jayway.jsonpath.PathNotFoundException" message="No results for path: $[&#039;access_token&#039;]">
      <![CDATA[com.jayway.jsonpath.PathNotFoundException: No results for path: $['access_token']
at com.jayway.jsonpath.internal.path.EvaluationContextImpl.getValue(EvaluationContextImpl.java:133)
at com.jayway.jsonpath.JsonPath.read(JsonPath.java:187)
at com.jayway.jsonpath.internal.JsonContext.read(JsonContext.java:102)
at com.jayway.jsonpath.internal.JsonContext.read(JsonContext.java:85)
at com.api.service.Base_MoneyMovement.API_clientCredentials(Base_MoneyMovement.java:72)
at com.stepdefs.Transactions_stepdefs.initiate_the_Client_Credentials_API_with_and_get_the_accessToken(Transactions_stepdefs.java:29)
at ✽.Initiate the Client_Credentials_API with 'loan_authorization' and '/apis'  get the accessToken(file:///D:/Jyoti/API/Restassured_WithBaseclass/RestAssured.zip_expanded/./src/test/resources/features/TestCases.feature:10)
]]>
    </error>
  </testcase> <!-- scenario -->
  <system-out/>
  <testcase name="scenario" time="5.173" classname="com.CucumberRunner_Assignment3">
    <error type="com.jayway.jsonpath.PathNotFoundException" message="No results for path: $[&#039;access_token&#039;]">
      <![CDATA[com.jayway.jsonpath.PathNotFoundException: No results for path: $['access_token']
at com.jayway.jsonpath.internal.path.EvaluationContextImpl.getValue(EvaluationContextImpl.java:133)
at com.jayway.jsonpath.JsonPath.read(JsonPath.java:187)
at com.jayway.jsonpath.internal.JsonContext.read(JsonContext.java:102)
at com.jayway.jsonpath.internal.JsonContext.read(JsonContext.java:85)
at com.api.service.Base_MoneyMovement.API_clientCredentials(Base_MoneyMovement.java:72)
at com.stepdefs.Transactions_stepdefs.initiate_the_Client_Credentials_API_with_and_get_the_accessToken(Transactions_stepdefs.java:29)
at ✽.Initiate the Client_Credentials_API with 'loan_authorization' and '/api'  get the accessToken(file:///D:/Jyoti/API/Restassured_WithBaseclass/RestAssured.zip_expanded/./src/test/resources/features/TestCases.feature:10)
]]>
    </error>
  </testcase> <!-- scenario -->
  <system-out/>
  <testcase name="scenario" time="12.588" classname="com.CucumberRunner_Assignment3"/>
  <system-out/>
  <testcase name="scenario" time="7.462" classname="com.CucumberRunner_Assignment3"/>
  <system-out/>
  <testcase name="scenario" time="9.205" classname="com.CucumberRunner_Assignment3"/>
  <system-out/>
  <testcase name="scenario" time="9.001" classname="com.CucumberRunner_Assignment3"/>
  <system-out/>
  <testcase name="scenario" time="4.610" classname="com.CucumberRunner_Assignment3">
    <error type="com.jayway.jsonpath.PathNotFoundException" message="No results for path: $[&#039;access_token&#039;]">
      <![CDATA[com.jayway.jsonpath.PathNotFoundException: No results for path: $['access_token']
at com.jayway.jsonpath.internal.path.EvaluationContextImpl.getValue(EvaluationContextImpl.java:133)
at com.jayway.jsonpath.JsonPath.read(JsonPath.java:187)
at com.jayway.jsonpath.internal.JsonContext.read(JsonContext.java:102)
at com.jayway.jsonpath.internal.JsonContext.read(JsonContext.java:85)
at com.api.service.Base_MoneyMovement.API_clientCredentials(Base_MoneyMovement.java:72)
at com.stepdefs.Transactions_stepdefs.initiate_the_Client_Credentials_API_with_and_get_the_accessToken(Transactions_stepdefs.java:29)
at ✽.Initiate the Client_Credentials_API with 'grant_type' and 'scope'  get the accessToken(file:///D:/Jyoti/API/Restassured_WithBaseclass/RestAssured.zip_expanded/./src/test/resources/features/TestCases.feature:61)
]]>
    </error>
  </testcase> <!-- scenario -->
  <system-out/>
  <testcase name="scenario" time="5.027" classname="com.CucumberRunner_Assignment3">
    <error type="com.jayway.jsonpath.PathNotFoundException" message="No results for path: $[&#039;access_token&#039;]">
      <![CDATA[com.jayway.jsonpath.PathNotFoundException: No results for path: $['access_token']
at com.jayway.jsonpath.internal.path.EvaluationContextImpl.getValue(EvaluationContextImpl.java:133)
at com.jayway.jsonpath.JsonPath.read(JsonPath.java:187)
at com.jayway.jsonpath.internal.JsonContext.read(JsonContext.java:102)
at com.jayway.jsonpath.internal.JsonContext.read(JsonContext.java:85)
at com.api.service.Base_MoneyMovement.API_clientCredentials(Base_MoneyMovement.java:72)
at com.stepdefs.Transactions_stepdefs.initiate_the_Client_Credentials_API_with_and_get_the_accessToken(Transactions_stepdefs.java:29)
at ✽.Initiate the Client_Credentials_API with 'grant_type' and 'scope'  get the accessToken(file:///D:/Jyoti/API/Restassured_WithBaseclass/RestAssured.zip_expanded/./src/test/resources/features/TestCases.feature:83)
]]>
    </error>
  </testcase> <!-- scenario -->
  <system-out/>
  <testcase name="scenario" time="9.209" classname="com.CucumberRunner_Assignment3"/>
  <system-out/>
  <testcase name="scenario" time="4.588" classname="com.CucumberRunner_Assignment3">
    <error type="com.jayway.jsonpath.PathNotFoundException" message="No results for path: $[&#039;access_token&#039;]">
      <![CDATA[com.jayway.jsonpath.PathNotFoundException: No results for path: $['access_token']
at com.jayway.jsonpath.internal.path.EvaluationContextImpl.getValue(EvaluationContextImpl.java:133)
at com.jayway.jsonpath.JsonPath.read(JsonPath.java:187)
at com.jayway.jsonpath.internal.JsonContext.read(JsonContext.java:102)
at com.jayway.jsonpath.internal.JsonContext.read(JsonContext.java:85)
at com.api.service.Base_MoneyMovement.API_clientCredentials(Base_MoneyMovement.java:72)
at com.stepdefs.Transactions_stepdefs.initiate_the_Client_Credentials_API_with_and_get_the_accessToken(Transactions_stepdefs.java:29)
at ✽.Initiate the Client_Credentials_API with 'grant_type' and 'scope'  get the accessToken(file:///D:/Jyoti/API/Restassured_WithBaseclass/RestAssured.zip_expanded/./src/test/resources/features/TestCases.feature:61)
]]>
    </error>
  </testcase> <!-- scenario -->
  <system-out/>
  <testcase name="scenario" time="14.737" classname="com.CucumberRunner_Assignment3"/>
  <system-out/>
  <testcase name="scenario" time="8.983" classname="com.CucumberRunner_Assignment3"/>
  <system-out/>
  <testcase name="scenario" time="9.427" classname="com.CucumberRunner_Assignment3"/>
  <system-out/>
  <testcase name="scenario" time="12.499" classname="com.CucumberRunner_Assignment3"/>
  <system-out/>
  <testcase name="scenario" time="12.075" classname="com.CucumberRunner_Assignment3"/>
  <system-out/>
  <testcase name="scenario" time="7.621" classname="com.CucumberRunner_Assignment3"/>
  <system-out/>
  <testcase name="scenario" time="11.241" classname="com.CucumberRunner_Assignment3"/>
  <system-out/>
  <testcase name="scenario" time="10.135" classname="com.CucumberRunner_Assignment3"/>
  <system-out/>
  <testcase name="scenario" time="9.229" classname="com.CucumberRunner_Assignment3"/>
  <system-out/>
</testsuite> <!-- com.CucumberRunner_Assignment3 -->
